# schema.yml

version: 2

sources:
  - name: raw            # alias pour simplifier les appels
    schema: gz_raw_data  # nom réel du dataset dans BigQuery
    tables:
      - name: raw_gz_sales
        alias: sales
      - name: raw_gz_product
        alias: product
      - name: raw_gz_ship
        alias: ship